[features]
seeds = false
[programs.localnet]
token_mint_lock = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
faucet = "9q3r2o4iRba85gDErhT7vNp5qGfzf92GnEiv823x8ozZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
